import { 
  Home,
  Bed,
  HeartPulse,
  Contact2,
  Ribbon,
  Ambulance,
  Pill,
  ActivityIcon,
  Users2,
  Settings,
  CreditCard,
  UserRound,
  Target
} from 'lucide-react';

export const sidebaNavLinks = [
    {
      label: "Dashboard Overview",
      route: "/dashboard",
      icon: <Home stroke='1.5' />,
      alt: "Home",
    },
    {
      label: "Patient Registration",
      route: "/dashboard/patient-registration",
      icon: <Contact2 stroke='1.5'/>,
      alt: "Patient Registration",
    },
    {
      label: "Consultation",
      route: "/dashboard/consultation",
      icon: <Ribbon stroke='1.5'/>,
      alt: "Consultation",
    },
    {
      label: "Treatment",
      route: "/dashboard/treatment",
      icon: <Ambulance stroke='1.5'/>,
      alt: "Treatment",
    },
    {
      label: "Pharmacy",
      route: "/dashboard/pharmacy",
      icon: <Pill stroke='1.5'/>,
      alt: "Pharmacy",
    },
    {
      label: "Diagnostics",
      route: "/dashboard/diagnostics",
      icon: <HeartPulse/>,
      alt: "Diagnostics",
    },
    {
      label: "Inpatients",
      route: "/dashboard/inpatients",
      icon: <Users2 stroke='1.5'/>,
      alt: "Inpatients",
    },
    {
      label: "Settings",
      route: "/dashboard/settings",
      icon: <Settings stroke='1.5'/>,
      alt: "Settings",
    },
    {
      label: "Billing",
      route: "/dashboard/billing",
      icon: <CreditCard stroke='1.5'/>,
      alt: "Billing",
    },
    {
      label: "Profile",
      route: "/dashboard/profile",
      icon: <UserRound stroke='1.5'/>,
      alt: "Profile",
    },
    {
      label: "Logout",
      route: "/dashboard/logout",
      icon: <Target stroke='1.5'/>,
      alt: "Logout",
    },
    {
      label: "Logout",
      route: "/dashboard/logout",
      icon: <Target stroke='1.5'/>,
      alt: "Logout",
    },
    {
      label: "Logout",
      route: "/dashboard/logout",
      icon: <Target stroke='1.5'/>,
      alt: "Logout",
    },
    {
      label: "Logout",
      route: "/dashboard/logout",
      icon: <Target stroke='1.5'/>,
      alt: "Logout",
    },
    {
      label: "Logout",
      route: "/dashboard/logout",
      icon: <Target stroke='1.5'/>,
      alt: "Logout",
    },
    {
      label: "Logout",
      route: "/dashboard/logout",
      icon: <Target stroke='1.5'/>,
      alt: "Logout",
    },
    {
      label: "Logout",
      route: "/dashboard/logout",
      icon: <Target stroke='1.5'/>,
      alt: "Logout",
    },
    {
      label: "Logout",
      route: "/dashboard/logout",
      icon: <Target stroke='1.5'/>,
      alt: "Logout",
    },
    {
      label: "Logout",
      route: "/dashboard/logout",
      icon: <Target stroke='1.5'/>,
      alt: "Logout",
    },
  ];